In [12]:
import pandas as pd


students = {
    'studentID': [101,102,103,104,105,108],
    'name':['ashok','Jaanvi','Shivam','Jamuna','lily','Abhi'],
    'Age': [24,22,24,26,21,24]
}

rseult = {
    'studentID': [101,102,103,104,105],
    'Subject': ['maths','java','c++','go','ruby'],
    'score': [88,75,90,55,86]
}

In [13]:
students = pd.DataFrame(students)
students

   studentID    name  Age
0        101   ashok   24
1        102  Jaanvi   22
2        103  Shivam   24
3        104  Jamuna   26
4        105    lily   21
5        108    Abhi   24

In [14]:
rseult = pd.DataFrame(rseult)
rseult

   studentID Subject  score
0        101   maths     88
1        102    java     75
2        103     c++     90
3        104      go     55
4        105    ruby     86

In [17]:
left_merge = pd.merge(students,rseult,on='studentID',how='left')
left_merge

   studentID    name  Age Subject  score
0        101   ashok   24   maths   88.0
1        102  Jaanvi   22    java   75.0
2        103  Shivam   24     c++   90.0
3        104  Jamuna   26      go   55.0
4        105    lily   21    ruby   86.0
5        108    Abhi   24     NaN    NaN

In [ ]:
right_merge = pd.merge(students,rseult,on='studentID',how='right')
right_merge

   studentID    name  Age Subject  score
0        101   ashok   24   maths   88.0
1        102  Jaanvi   22    java   75.0
2        103  Shivam   24     c++   90.0
3        104  Jamuna   26      go   55.0
4        105    lily   21    ruby   86.0
5        108    Abhi   24     NaN    NaN

In [18]:
outer_merge = pd.merge(students,rseult,on='studentID',how='outer')
outer_merge

   studentID    name  Age Subject  score
0        101   ashok   24   maths   88.0
1        102  Jaanvi   22    java   75.0
2        103  Shivam   24     c++   90.0
3        104  Jamuna   26      go   55.0
4        105    lily   21    ruby   86.0
5        108    Abhi   24     NaN    NaN

In [22]:
data1 = pd.read_csv("credit_card_transactions.csv")
data1.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland

In [23]:
data2 = pd.read_csv("customer_details.csv")
data2.head()

   Customer_ID  Age Gender Membership_Level
0         1001   58   Male           Silver
1         1002   35   Male           Silver
2         1003   65   Male             Gold
3         1004   52   Male             Gold
4         1005   20   Male           Silver

In [ ]:
print(data1.shape)
print(data2.shape)

(5500, 10)
(2000, 4)

In [24]:
outer_merge = pd.merge(data1,data2,on='Customer_ID',how='outer')
outer_merge

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location,Age,Gender,Membership_Level
0,102592.0,1000,2023-04-19,Online,Amazon,Electronics,3324.12,UPI,Declined,West Joshua,NaN,NaN,NaN
1,102502.0,1001,2023-04-15,POS,Apple Store,Electronics,882.18,Credit Card,Approved,Port Cathyland,58.0,Male,Silver
2,NaN,1002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,Male,Silver
3,100926.0,1003,2023-02-08,Online,Target,Electronics,2776.66,PayPal,Approved,Lake Peterbury,65.0,Male,Gold
4,104143.0,1003,2023-06-22,Mobile Payment,Target,Travel,3269.75,PayPal,Approved,Monicaside,65.0,Male,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6015,103463.0,4996,2023-05-25,Mobile Payment,Uber,Entertainment,4644.16,Credit Card,Approved,Ramirezbury,NaN,NaN,NaN
6016,100848.0,4998,2023-02-05,Online,Walmart,Groceries,87.50,Credit Card,Approved,Lake Dylanmouth,NaN,NaN,NaN
6017,101649.0,4998,2023-03-10,POS,Apple Store,Groceries,4494.02,UPI,Approved,Adamfort,NaN,NaN,NaN
6018,101853.0,4998,2023-03-19,Online,Netflix,Groceries,612.89,Debit Card,Approved,East Lori,NaN,NaN,NaN
6019,104826.0,4998,2023-07-21,ATM,Netflix,Clothing,804.16,Debit Card,Approved,East Jaime,NaN,NaN,NaN

In [ ]:
print(outer_merge.isnull().sum(
    ..............................................
))

Transaction_ID         520
Customer_ID              0
Transaction_Date       520
Transaction_Type       520
Merchant               520
Category               520
Amount                 520
Payment_Mode           520
Transaction_Status     520
Location               520
Age                   2751
Gender                2751
Membership_Level      2751
dtype: int64