In [43]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\itvedant cr4-10\appdata\local\programs\python\python311\lib\site-packages (2.2.1)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\itvedant cr4-10\appdata\local\programs\python\python311\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\itvedant cr4-10\appdata\roaming\python\python311\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\itvedant cr4-10\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\itvedant cr4-10\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\itvedant cr4-10\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [44]:
import pandas as pd
data = {
    'store':['North','South','East','East','North','North','South','South','South','North'],
    'product':['laptop','phone','tablet','phone','tablet','phone','tablet','laptop','laptop','tablet'],
    'sales':[1200,3400,2000,1500,6000,200,600,800,1204,1800],
    'qt':[2,3,4,2,4,6,7,2,2,8]
}

# DataFrame

df = pd.DataFrame(data)
print(df)

   store product  sales  qt
0  North  laptop   1200   2
1  South   phone   3400   3
2   East  tablet   2000   4
3   East   phone   1500   2
4  North  tablet   6000   4
5  North   phone    200   6
6  South  tablet    600   7
7  South  laptop    800   2
8  South  laptop   1204   2
9  North  tablet   1800   8

In [45]:
# group by one column -> total sales per store 
store_sales = df.groupby('store').sum()
print(store_sales)

                       product  sales  qt
store
East               tabletphone   3500   6
North  laptoptabletphonetablet   9200  20
South  phonetabletlaptoplaptop   6004  14

In [46]:
# group by one column -> total sales per product 
product_sales = df.groupby('product').sum()
print(product_sales)

                       store  sales  qt
product
laptop       NorthSouthSouth   3204   6
phone         SouthEastNorth   5100  11
tablet   EastNorthSouthNorth  10400  23

In [47]:
Sales_by_store = df.groupby('store')['sales'].sum()
print(Sales_by_store)

store
East     3500
North    9200
South    6004
Name: sales, dtype: int64

In [48]:
#agg()
summary = df.groupby('store').agg({
    'sales' :['sum','mean','count'],
    'qt':'sum'
})

print(summary)

      sales                qt
        sum    mean count sum
store
East   3500  1750.0     2   6
North  9200  2300.0     4  20
South  6004  1501.0     4  14

In [49]:
# group by using multiple column 
by_store_product = df.groupby(['store','product'])['sales'].sum()
print(by_store_product)

store  product
East   phone      1500
       tablet     2000
North  laptop     1200
       phone       200
       tablet     7800
South  laptop     2004
       phone      3400
       tablet      600
Name: sales, dtype: int64

In [50]:
#unstack()
print(by_store_product.unstack(fill_value=0))

product  laptop  phone  tablet
store
East          0   1500    2000
North      1200    200    7800
South      2004   3400     600

In [51]:
def sales_value(group):
    group['High_value'] = group['sales']>1500
    return group

#apply()
result = df.groupby('store').apply(sales_value)
print(result)

print(result[['store','sales','High_value']])

         store product  sales  qt  High_value
store
East  2   East  tablet   2000   4        True
      3   East   phone   1500   2       False
North 0  North  laptop   1200   2       False
      4  North  tablet   6000   4        True
      5  North   phone    200   6       False
      9  North  tablet   1800   8        True
South 1  South   phone   3400   3        True
      6  South  tablet    600   7       False
      7  South  laptop    800   2       False
      8  South  laptop   1204   2       False
         store  sales  High_value
store
East  2   East   2000        True
      3   East   1500       False
North 0  North   1200       False
      4  North   6000        True
      5  North    200       False
      9  North   1800        True
South 1  South   3400        True
      6  South    600       False
      7  South    800       False
      8  South   1204       False

C:\Users\Itvedant CR4-10\AppData\Local\Temp\ipykernel_3000\2834032325.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df.groupby('store').apply(sales_value)

In [52]:
def sales_value(group):
    group['High_value'] = group['sales']>1500
    return group

#apply()
result = df.groupby('product').apply(sales_value)
print(result)

print(result[['product','sales','High_value']])

           store product  sales  qt  High_value
product
laptop  0  North  laptop   1200   2       False
        7  South  laptop    800   2       False
        8  South  laptop   1204   2       False
phone   1  South   phone   3400   3        True
        3   East   phone   1500   2       False
        5  North   phone    200   6       False
tablet  2   East  tablet   2000   4        True
        4  North  tablet   6000   4        True
        6  South  tablet    600   7       False
        9  North  tablet   1800   8        True
          product  sales  High_value
product
laptop  0  laptop   1200       False
        7  laptop    800       False
        8  laptop   1204       False
phone   1   phone   3400        True
        3   phone   1500       False
        5   phone    200       False
tablet  2  tablet   2000        True
        4  tablet   6000        True
        6  tablet    600       False
        9  tablet   1800        True

C:\Users\Itvedant CR4-10\AppData\Local\Temp\ipykernel_3000\2482972243.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df.groupby('product').apply(sales_value)

In [53]:
# Dataset
practice = pd.DataFrame({
    'Team':['A','B','A','B','A','B'],
    'player':['X','Y','Z','W','X','Y'],
    'points':[10,15,8,20,12,18]
})
print(practice)

  Team player  points
0    A      X      10
1    B      Y      15
2    A      Z       8
3    B      W      20
4    A      X      12
5    B      Y      18

In [54]:
# Tasks:
#1. Total points per team

team_total = practice.groupby('Team')['points'].sum()

print(team_total)

Team
A    30
B    53
Name: points, dtype: int64

In [55]:
team_avg = practice.groupby('player')['points'].mean()
print(team_avg)

player
W    20.0
X    11.0
Y    16.5
Z     8.0
Name: points, dtype: float64

In [56]:
import pandas as pd

# Sample sales data
data = {
    'Order_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Date': ['2024-01-05', '2024-01-10', '2024-01-15', '2024-02-01', '2024-02-05',
             '2024-02-10', '2024-03-01', '2024-03-05', '2024-03-10', '2024-01-20'],
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Laptop', 'Phone', 
                'Tablet', 'Mouse', 'Keyboard', 'Phone', 'Laptop'],
    'Category': ['Electronics', 'Accessories', 'Accessories', 'Electronics', 'Electronics',
                 'Electronics', 'Accessories', 'Accessories', 'Electronics', 'Electronics'],
    'Sales': [75000, 1200, 2500, 80000, 45000, 30000, 1500, 2800, 42000, 72000],
    'Quantity': [1, 5, 3, 1, 2, 3, 4, 2, 1, 2],
    'City': ['Mumbai', 'Delhi', 'Bangalore', 'Mumbai', 'Delhi', 
             'Bangalore', 'Mumbai', 'Delhi', 'Bangalore', 'Mumbai']
}

df_temp = pd.DataFrame(data)
df_temp.to_csv('sales_data.csv', index=False)

In [57]:
city_total = df_temp.groupby('City')['Sales'].sum()

print(city_total)

City
Bangalore     74500
Delhi         49000
Mumbai       228500
Name: Sales, dtype: int64

In [58]:
city_avg = df_temp.groupby('Category')['Quantity'].mean().round(2)

print(city_avg)

Category
Accessories    3.50
Electronics    1.67
Name: Quantity, dtype: float64

In [59]:
city_avg = df_temp.groupby(['City','Category'])['Sales'].mean().round(2)

print(city_avg)

City       Category
Bangalore  Accessories     2500.00
           Electronics    36000.00
Delhi      Accessories     2000.00
           Electronics    45000.00
Mumbai     Accessories     1500.00
           Electronics    75666.67
Name: Sales, dtype: float64

In [60]:
order_city = df_temp.groupby('City')['Order_ID'].count()

print(order_city)

City
Bangalore    3
Delhi        3
Mumbai       4
Name: Order_ID, dtype: int64

In [61]:
city_sales = df_temp.groupby('City').agg(
    {
    'Sales':['sum','mean','max'],
    'Quantity':'sum'
}
).round(2)

print(city_sales)

            Sales                  Quantity
              sum      mean    max      sum
City
Bangalore   74500  24833.33  42000        7
Delhi       49000  16333.33  45000        9
Mumbai     228500  57125.00  80000        8

In [62]:
import pandas as pd
# melt
#example
data = pd.DataFrame(
    {
        'store':["North","South","East"],
        '2021':[1200,800,900],
        '2022':[1500,900,1100],
        '2023':[1400,850,1000]
    }
)

data

   store  2021  2022  2023
0  North  1200  1500  1400
1  South   800   900   850
2   East   900  1100  1000

In [ ]:
# store | year | sales
# North | 2021 | 1200

NameError: name 'store' is not defined

In [ ]:
#unpivot pd.melt()
long_df = pd.melt(
    wide_df,#data
    id_vars=['store'],#columns
    value_vars =['2021','2022'],#column to melt
    var_name='year',#new col
    value_name='sales' #new col
)
long_df

   store  year  sales
0  North  2021   1200
1  South  2021    800
2   East  2021    900
3  North  2022   1500
4  South  2022    900
5   East  2022   1100

In [ ]:
long_df.to_csv("Data.csv")

In [ ]:
wide_df = pd.DataFrame(
    {
        'store':['North','South','East'],
        'Product':['Laptop','Mouse','Keyboard'],
        '2021':[1200,800,900],
        '2022':[1500,900,1100],
        '2023':[1400,850,1000],
        'price_day1':[120,450,650],
        'price_day2':[560,890,780]
    }
)

In [ ]:
long_df = pd.melt(
    wide_df,#data
    id_vars=['Product'],#columns
    value_vars =['price_day1','price_day2'],#column to melt
    var_name='price day',#new col
    value_name='price' #new col
)
long_df

    Product   price day  price
0    Laptop  price_day1    120
1     Mouse  price_day1    450
2  Keyboard  price_day1    650
3    Laptop  price_day2    560
4     Mouse  price_day2    890
5  Keyboard  price_day2    780

In [ ]:
#melt all
long_all = pd.melt(
    wide_df,
    id_vars=['store'],
    var_name='year',
    value_name='sales'

)
long_all

    store        year     sales
0   North     Product    Laptop
1   South     Product     Mouse
2    East     Product  Keyboard
3   North        2021      1200
4   South        2021       800
5    East        2021       900
6   North        2022      1500
7   South        2022       900
8    East        2022      1100
9   North        2023      1400
10  South        2023       850
11   East        2023      1000
12  North  price_day1       120
13  South  price_day1       450
14   East  price_day1       650
15  North  price_day2       560
16  South  price_day2       890
17   East  price_day2       780

In [69]:
long_all1 = pd.melt(
    wide_df,
    id_vars=['Product'],
    var_name='year',
    value_name='sales'
)

long_all1

     Product        year  sales
0     Laptop       store  North
1      Mouse       store  South
2   Keyboard       store   East
3     Laptop        2021   1200
4      Mouse        2021    800
5   Keyboard        2021    900
6     Laptop        2022   1500
7      Mouse        2022    900
8   Keyboard        2022   1100
9     Laptop        2023   1400
10     Mouse        2023    850
11  Keyboard        2023   1000
12    Laptop  price_day1    120
13     Mouse  price_day1    450
14  Keyboard  price_day1    650
15    Laptop  price_day2    560
16     Mouse  price_day2    890
17  Keyboard  price_day2    780

In [72]:
wide_df['Manager'] =['rupali','joy','ashok'] 
long_df = pd.melt(
    wide_df,#data
    id_vars=['store','Manager'],#columns
    value_vars =['2021','2022','2023'],#column to melt
    var_name='year',#new col
    value_name='sales' #new col
)
long_df

   store Manager  year  sales
0  North  rupali  2021   1200
1  South     joy  2021    800
2   East   ashok  2021    900
3  North  rupali  2022   1500
4  South     joy  2022    900
5   East   ashok  2022   1100
6  North  rupali  2023   1400
7  South     joy  2023    850
8   East   ashok  2023   1000

In [73]:
wide_df['Manager'] =['rupali','joy','ashok'] 
long_df = pd.melt(
    wide_df,#data
    id_vars=['store','Manager','year','price'],#columns
    value_vars =['2021','2022','2023'],#column to melt
    var_name='year',#new col
    value_name='sales' #new col
)
long_df

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['year', 'price']"

In [77]:
long_all = pd.melt(
    wide_df,
    id_vars=['store'],['Product'],
    var_name='year',
    value_name='sales'

)
long_all

SyntaxError: positional argument follows keyword argument (348956712.py, line 7)

In [80]:
scores_wide = pd.DataFrame({
    'Student': ['Ali', 'Beth', 'Cathy'],
    'Math': [85, 90, 78],
    'Science': [88, 92, 80],
    'English': [90, 85, 88]
})
scores_wide

#output
#student | Subject | Score

  Student  Math  Science  English
0     Ali    85       88       90
1    Beth    90       92       85
2   Cathy    78       80       88

In [ ]:
scores_long = pd.melt(
    scores_wide,
    id_vars=['Student'],  
    var_name='Subject',       
    value_name='Score'        
)

print(scores_long)

  Student  Subject  Score
0     Ali     Math     85
1    Beth     Math     90
2   Cathy     Math     78
3     Ali  Science     88
4    Beth  Science     92
5   Cathy  Science     80
6     Ali  English     90
7    Beth  English     85
8   Cathy  English     88

In [85]:
result = scores_long.groupby('Subject')['Score'].mean()
result

Subject
English    87.666667
Math       84.333333
Science    86.666667
Name: Score, dtype: float64